---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

App\Web\BlogHolder:
  allowed_children:
    - App\Web\PostPage

# UTF8MB4 has limited support in older MySQL versions.
# Remove this configuration if you experience issues.
---
Name: myproject-database
---
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

# Extension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - App\Web\SiteConfigExtension

# CORS
SilverStripe\GraphQL\Controller:
  cors:
    Enabled: true
    Allow-Origin: '*'
